name: Run algorithm

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Compile source files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile executable
        run: scripts/build.sh

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: build/*.exe

  solve:
    name: Run algorithm
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: executable
          path: build/

      - name: Update executable permission
        run: chmod +x build/*.exe

      - name: Run algorithm
        run: |
          exitcode=0
          set +e

          report_error() {
            this_exitcode=$?

            if [ $this_exitcode -ne 0 ]
            then
              echo "::warning::Exit code $this_exitcode at run #$i"
              exitcode=1
            fi
          }

          echo "Test,A* (ms),BFS (ms)" > summary.csv

          find samples -maxdepth 1 -type f -name "*.txt" -print0 | while IFS= read -r -d $'\0' f
          do
            for i in $(seq 1 20)
            do
              echo "RUN #$i of \"$f\""
              python scripts/benchmark.py "$f" > input.txt
              report_error

              echo -n "\"$f\"," >> summary.csv

              cat input.txt | build/a_star.exe 2>&1 >/dev/null | grep -o '[0-9]\+ ms' | grep -o '[0-9]\+' | tr '\n' ' ' | sed 's/ $//' >> summary.csv
              report_error

              echo -n "," >> summary.csv

              cat input.txt | build/bfs.exe 2>&1 >/dev/null | grep -o '[0-9]\+ ms' | grep -o '[0-9]\+' >> summary.csv
              report_error

            done
          done

      - name: Upload summary table
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary.csv
